variable "rgs" {}
variable "vnets" {}
variable "subnets" {}
variable "BHs" {}
variable "kv" {}
variable "nsgs" {}
variable "security_rule" {}
variable "vms" {}
variable "lbs" {}
variable "appgws" {}
variable "storage_accounts" {}
variable "peerings" {}